### ISSUE TITLE
useLocalStorageValue yields undefined on firstRender if initializeWithValue not set

### ISSUE THREAD

**Issue by Evalon** [react-hookz/web#1002]
### What is the current behavior?

`useLocalStorageValue` yields undefined on first render if `initializeWithValue` not set to true and on second render yield actual value from localStorage.

https://codesandbox.io/s/wispy-forest-qmrlzn?file=/src/App.tsx

### What is the expected behavior?

`initializeWithValue: true` should be default behavior based on documentation and previous behaviour.

### Environment Details

- _`@react-hookz/web` version: 17.0
- _`react` version: 18.2 
- _`react-dom` version: 18.2
- _`typescript` version: 4.8.4
- _OS: macos
- _Browser: chrome
- _Did this work in previous versions? yes

**Comment by ArttuOll** [comment]
Thanks for the bug report!

I managed to repeat this. Indeed, it seems that the default value of `initializeWithValue` is `false` even though in the code (and in the docs) it definitely looks like it should be `true`.

I'm looking into this.
