### ISSUE TITLE
useLocalStorageValue will cause infinite loop

### ISSUE THREAD

**Issue by vip30** [react-hookz/web#1014]
### What is the current behavior?

set function will be changed after the new value has been set

### Steps to Reproduce

```
  const { set } = useLocalStorageValue("test", {
    defaultValue: 1
  });
  useEffect(() => {
    set(value => (value ?? 1) + 1);
  }, [set]);
  ```

### What is the expected behavior?

Should not trigger the effect

### Environment Details

- _`@react-hookz/web` version: 18.0.0
- _`react` version: 18.2.0
- _`react-dom` version: 18.2.0 
- _`typescript` version: 4.8.4
- _OS: macOS
- _Browser: Chromse
- _Did this work in previous versions? yes

**Comment by ArttuOll** [comment]
Huge thanks for notifying us about this!
