### ISSUE TITLE
useGlobalState

### ISSUE THREAD

**Issue by jpwallace22** [react-hookz/web#1119]
## New Features
I would like to add a `useGlobalState` hook

### What is the new or updated feature that you are suggesting?
Prop drilling is a pain and Context are not only start to get out of hand the way they are nested, but they cause a ton of rerenders and are a pain to configure. I propose a `useGlobalState` hook that can extend the features of useState, but globally. 

```ts
function useGlobalState<T>(config: GlobalSateConfig<T>): readonly [T, (stateOrSetter: T) => void]
```

### Why should this feature be included?
So people can seamlessly and easily add a legible and easy to manage state option for global state

**🚨 I will implement this hook myself. I just want to run it by the team before I start 🚨**

**Comment by xobotyi** [comment]
Why not to leave it to existing libraries?
redux/recoil/there is a ton others..

**Comment by jpwallace22** [comment]
@xobotyi a simple useGlobalState hook will fill the gap between "context hell" and having to add a giant dependency for a couple of pieces of state. In smaller websites it's not unlikely to only need a couple of pieces of global state.

**Comment by ArttuOll** [comment]
Client-state management libraries generally aren't that big (at least the ones I'm aware of), with the exception of Recoil ([79 kB minified](https://bundlephobia.com/package/recoil@0.7.6)). [Jotai](https://bundlephobia.com/package/jotai@2.0.0), [Zustand](https://bundlephobia.com/package/zustand@4.3.2) and [Redux](https://bundlephobia.com/package/redux@4.2.1) are all well below 10 kB minified.

In my opinion, `useContext` + `useReducer` combination gets you pretty far client-state management-wise. When that's not enough, a dedicated state management library comes into question. I don't think there's a middle ground between those, but let me know if you think I'm mistaken.

Implementing global state management is tricky business and I don't think we should duplicate the efforts those libraries are making. This is the same rationale we used when we decided not to port navigation-related hooks from react-use in #33 and head-element modifying hooks in #1004 .

**Comment by jpwallace22** [comment]
@ArttuOll I guess more than the size of the dependency its the amount that goes into it. Its usually a couple of dependencies and at least a couple files in order to set up basic global state. For smaller websites that don't usually need something so robust, I think its useful. However, it's totally up to yall.

**Comment by jpwallace22** [comment]
After more digging, I feel like you're right. I'm just too used to using Redux and hate it some much. Now that I am looking at other libraries, I would probably just use one of those instead.

**Comment by ArttuOll** [comment]
Yeah, I feel like Jotai's atoms might be what you want if you only need a couple of pieces global state. Closing this now.
