### ISSUE TITLE
[Port] useCopyToClipboard

### ISSUE THREAD

**Issue by Myzel394** [react-hookz/web#1244]
(this issue isn't a feature request but rather a draft on how to implement `useCopyToClipboard`)

## Implementation of `useCopyToClipboard`

I was thinking about porting `useCopyToClipboard` (code: https://github.com/streamich/react-use/blob/master/src/useCopyToClipboard.ts), but first wanted to sketch out how it should look like before actually implementing it.

My personal goal would be to achieve something like this:

```typescript
const [copy, {failed}] = useCopyToClipboard({
  debug: true,
  onCopy: (clipboardData) => null,
});

return (
  <div>
    <p>{failed && "Copying failed :("}</p>
    <button onClick={() => copy("Hello World", {format: "text/plain"})}>Copy</button>
  </div>
);
```

so the typescript definition would look something like this:

```typescript
// Based on https://github.com/sudodoki/copy-to-clipboard
interface UseCopyToClipboardOptions {
  debug: boolean;
  onCopy: (clipboardData: object) => void;
}

interface UseCopyToClipboardFunctionOptions {
  format: string;
}

function useCopyToClipboard(options: UseCopyToClipboardOptions): [((options: Partial<UseCopyToClipboardFunctionOptions>) => void), {failed: boolean}];
```

(I hope this code contains no error, I drafted it in the GitHub editor)

Also note that according to [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard), we can only copy `string`s.

I was thinking about adding a `timeout` option to the hook so that `failed` automatically resets after some time.

---

What do you think? Should we implement `useCopyToClipboard` this way?

**Comment by malavshah9** [comment]
@Myzel394  Have you seen [this?](https://github.com/react-hookz/web/pull/883)

**Comment by xobotyi** [comment]
As maintainers team agreed to not to port this hook - closing the issue.
