### ISSUE TITLE
Unable to run cleanup in useDebouncedEffect

### ISSUE THREAD

**Issue by Kyzegs** [react-hookz/web#1332]
### What is the current behavior?

`useDebouncedEffect` does nothing with the cleanup function.

### Steps to Reproduce

[Here's a StackBlitz Edit with the issue](https://stackblitz.com/edit/stackblitz-starters-zbykcp?file=src%2FApp.tsx). Although, it seems that StackBlitz does some sort of full refresh. You can see in the console that the `console.log` in the cleanup function never gets called.

In my own project with HMR it adds a new listener every time without unsubscribing, causing a multitude of API calls:
![image](https://github.com/react-hookz/web/assets/45851377/291d5b8d-00e3-4114-b0fd-bd57c867ac22)

### What is the expected behavior?

The `useDebouncedEffect` should allow for a cleanup function.

### Environment Details

- _`@react-hookz/web` version:_ 23.0.1
- _`react` version:_ 18.2.0
- _`react-dom` version:_ 18.2.0
- _`typescript` version:_ 5.1.3
- _OS:_ Windows 10
- _Browser:_ Google Chrome Version 115.0.5790.111 (Official Build) (64-bit)
- _Did this work in previous versions?_: Nope

**Comment by Kyzegs** [comment]
I just noticed that it's stated in the docs. Any reason why there's no support for a cleanup function?

**Comment by xobotyi** [comment]
Debounce function called outside the react lifecycle - effect happened, and if there ware no similar calls within timeframe - actual effect is invoked (hence debouncing).
