### ISSUE TITLE
`useAsync` should return not undefined `state.result` if `initialValue` is set

### ISSUE THREAD

**Issue by nikolay-borzov** [react-hookz/web#134]
### Prior Issues

None

### What is the current behavior?

`state.result` returned from `useAsync` with `initialValue` set has type `Result | undefined`. But JSDoc says 

> Value that will be set on initialisation, before the async function is executed.

I'd expect `useAsync` handle `initialValue` as `useState` does. Look at typings:

```
function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
function useState<S = undefined>(): [S | undefined, Dispatch<SetStateAction<S | undefined>>];
```

### Steps to Reproduce

```
const [{ result: initialData }] = useAsync(
  myAsyncFunction,
  [paramA],
  {
    initialValue: "RESULT",
  },
);

// Has type "string" | undefined
initialData 
```

### What is the expected behavior?

`initialData` should have type "string"

### Environment Details

- _`@react-hookz/web` version:_ 2.2.0
- _`react` version:_ 16.14.0
- _`react-dom` version:_ 16.14.0
- _`typescript` version:_ 4.3.2
- _OS:_ Windows
- _Browser:_ Chrome
- _Did this work in previous versions?_ Unknown

**Comment by xobotyi** [comment]
`useState` is way easier to type that way, but nevertheless i'll fix today
