### ISSUE TITLE
Seems like the types with #root import is not working

### ISSUE THREAD

**Issue by vip30** [react-hookz/web#1477]
### What is the current behavior?

Not able to resolve the types 
![image](https://github.com/react-hookz/web/assets/4260833/40d94e7a-9331-4fc3-bb89-e8b7987cc4a8)

### Steps to Reproduce

Install the latest version and check the types on import path

### What is the expected behavior?

Should resolve it correct

### Environment Details

- _`@react-hookz/web` version: latest

**Comment by xobotyi** [comment]
import aliases been ditched in [v24.0.3](https://github.com/react-hookz/web/releases/tag/v24.0.3) as it was breaking distribution.
