### ISSUE TITLE
Unexpected regexp behavior in useThrottledEffect demo

### ISSUE THREAD

**Issue by alev000** [react-hookz/web#1482]
[This demo](https://react-hookz.github.io/web/?path=/docs/lifecycle-usethrottledeffect--example) for useThrottledEffect exhibits some strange behavior. To reproduce, try slowly entering the string `a1aaaaaa` into the text box, and you'll see the status toggle repeatedly between "no digits" and "has digits".

I think the regexp in [this line](https://github.com/react-hookz/web/blob/52bd863c1c5ec78084213bcde6bcc5cee054cfd3/src/useThrottledEffect/__docs__/example.stories.tsx#L5) should drop the "global" flag. From [these docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test):

> JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags set (e.g., /foo/g or /foo/y). They store a [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) from the previous match.

**Comment by alev000** [comment]
Same for [the useDebouncedEffect demo](https://react-hookz.github.io/web/?path=/docs/lifecycle-usedebouncedeffect--example)

**Comment by xobotyi** [comment]
Yep, this is a demo issue -- as all the examples and documentation will be rewritten soon - closing this issue.
