### ISSUE TITLE
`useCheckAPI` hook with checks for APIs availability

### ISSUE THREAD

**Issue by mskVitalii** [react-hookz/web#1555]
## useCheckAPI
This hook would check for the availability of various browser APIs.

### Motivation
This hook is essential for supporting older browsers and ensuring compatibility across different environments. It would allow developers to gracefully handle scenarios where certain browser APIs are not available.

### Implementation
I am willing to implement this feature myself. Please reach out to me on Discord to guide me on how to get started with the project.

### Example Usage
```typescript
import { useCheckAPI } from 'react-hookz';

const MyComponent = () => {
  const isServiceWorkerAvailable = useCheckAPI('serviceWorker');
  const isLocalStorageAvailable = useCheckAPI('localStorage');

  if (!isServiceWorkerAvailable) {
    console.log('Service Worker API is not supported in this browser.');
  }

  return (
    <div>
      {isLocalStorageAvailable ? 'LocalStorage is available' : 'LocalStorage is not available'}
    </div>
  );
};
```
AND/OR
```typescript
// check all services as an object
const servicesStatuses = useCheckAPI();
// servicesStatuses.localStorage -- true
```

**Comment by xobotyi** [comment]
moving here response from Discord:

In such way i don't see how this hook could be useful.

1) These things are constants, they wont change over time, it is either supported by browser / shimmed by corejs or not. Thus there is no sense of making hook out of it, it's state wont change over time.
2) It is literally shorter to write `window.WebAssembly !== undefined` rather `isBrowserAPISupported('WebAssembly')` 
Hook would have been called `isBrowserAPISupported` as we're checking browser APIs availability, not some random HTTP or other API.

I'm not trying to somehow bury development of hook, I just not able to see any usefulness of it and thus nit able to justify spending time to develop it 😦
As i see it, these checks should be calculated once per bundle and stored within constant like `export const IS_GEOLOCATION_AVAILABLE = Boolean(navigator.geolocation);` or rather checked directly in-place at all.
As there is no additional performance cost to check truthfulness of object's property existence compared to boolean constant of module check.
Whereas usage of a hook will add way more significant performance hit.

**Comment by xobotyi** [comment]
Closing the issue due to lack of further response from the author.
