### ISSUE TITLE
useMediaQuery Safari support

### ISSUE THREAD

**Issue by grind-t** [react-hookz/web#242]
Hi! According to [can i use](https://caniuse.com/mdn-api_mediaquerylist): _"Prior to Safari 14, MediaQueryList is based on EventTarget, so you must use addListener() and removeListener() to observe media query lists."_. Is it possible to improve support for the Safari by checking if the addEventListenet/removeEventListener functions exist?

Some possible solutions: [try/catch](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/src/useMediaQuery.js), [check if undefined](https://github.com/jaredLunde/react-hook/blob/master/packages/media-query/src/index.tsx).

**Comment by xobotyi** [comment]
That fckn apple with their "own way"
