### ISSUE TITLE
useNetwork should be useNetworkState

### ISSUE THREAD

**Issue by kunjee17** [react-hookz/web#251]
## What docs page needs to be fixed?

- **Section**:
- useNetwork
- **Page**:

## What is the problem?
useNetwork should be renamed to useNetworkState
## What should be changed to fix the problem?
useNetwork should be renamed to useNetworkState

**Comment by JoeDuncko** [comment]
@xobotyi thoughts?

**Comment by xobotyi** [comment]
Well it should, since hook is `useNetworkState` already. Seems that I've missed docs refactoring🤦‍♂️
