### ISSUE TITLE
[querySubscribe()]: mql_1.addEventListener is not a function

### ISSUE THREAD

**Issue by fcisio** [react-hookz/web#292]
### What is the current behavior?

`useMediaQuery`'s `querySubscribe()` fails on iOS 12

> mql_1.addEventListener is not a function. (In 'mql_1.addEventListener('change', listener, { passive: true })', 'mql_1.addEventListener' is undefined)

### Steps to Reproduce

On iOS 12

1. Add a `useMediaQuery`
2. Serve to the device

### What is the expected behavior?

The project should run without bugs and warnings

### Environment Details

- _`@react-hookz/web` version:_ 7.0.0
- _`react` version:_ 17.0.2
- _`react-dom` version:_ 17.0.2
- _Browser:_ All IOS Browsers
- _Did this work in previous versions?_ No

**Comment by xobotyi** [comment]
As i dont have access to apple devices - you have to dig it yourself 😅

**Comment by JoeDuncko** [comment]
I'll take a look at this. Still, PRs appreciated if you figure out what's going on @fcisio !

**Comment by JoeDuncko** [comment]
Hi @fcisio . I've tested this on my iOS 14 device, and couldn't recreate this. I then checked this with iOS 12.4, and also couldn't recreate this.

Could you give me more info on what specific iOS 12 version you are on, and which device you are using? Thanks!

**Comment by JoeDuncko** [comment]
Update: I also tested on an iOS simulator running 12.0. No luck reproducing this bug.

**Comment by fcisio** [comment]
I'll try to test this week, but I think the issue might simply be coming from these if statements.
The current syntax often causes me issues in my own code, working with Gatsby mostly.
```js
if (mql.addEventListener)
if (mql.removeEventListener)
```

They could be refactored to this syntax, which seems less buggy for me

```js
if ("addEventListener" in mql)
if ("removeEventListener" in mql)
```

>

**Comment by JoeDuncko** [comment]
@fcisio Any luck reproducing this? I'm happy to just make that syntax change, but would like to make sure that actually fixes the problem.

**Comment by fcisio** [comment]
I won't be able to test this before 2 weeks.
I'll get to it as soon as I can

**Comment by JoeDuncko** [comment]
@fcisio No issues! Thanks!

**Comment by xobotyi** [comment]
Closing this issue dow to no response.

@fcisio feel free to reopen the issue if error still not solved.
