### ISSUE TITLE
Support leading option for useDebouncedCallback

### ISSUE THREAD

**Issue by nghiepit** [react-hookz/web#318]
### What is the new or updated feature that you are suggesting?
Support `leading` and `trailing` options  for `useDebouncedCallback`.

### Why should this feature be included?
It's a common feature of debounce
Example:
https://lodash.com/docs/4.17.15#debounce
https://github.com/xnimorz/use-debounce#leadingtrailing-calls

**Comment by xobotyi** [comment]
What for?
leading = throttle
trailing = debounce

We have both of these hooks.

**Comment by nghiepit** [comment]
thanks @xobotyi

**Comment by ilyasmez** [comment]
@nghiepdev  @xobotyi leading != throttle, you might still want the same debounced logic (the effect to run only when the last call is X ms old), while still running the first call immediately.

Example of "abc" typing in an input field with 200ms delay:

Without leading
```
                                 RUN
[a]         [b]        [c]   (200ms later)
```

With leading
```
RUN                              RUN
[a]         [b]        [c]   (200ms later)
```


Throttle on the other handle will run after a fixed 200ms, even if the user is still typing (for a longer example than "abc" of course).

Debounced is often the right option for input fields, and having a "leading" option is useful when needing to trigger something immediately after the user start typing (e.g. show search page, handle input clearing using a button, etc.)
