### ISSUE TITLE
Include example import statements on all docs pages

### ISSUE THREAD

**Issue by JoeDuncko** [react-hookz/web#319]
## What docs page needs to be fixed?

- **Section**:
- **Page**: All

## What is the problem?

It can be confusing for new users to figure out where to import hooks from, especially `useCookieValue`, which breaks our import patterns.

## What should be changed to fix the problem?

We should include example import statements on all docs pages

**Comment by xobotyi** [comment]
Initiative is punishable - you're doing it😅🤪

**Comment by JoeDuncko** [comment]
@xobotyi I'm cool with that, lol
