### ISSUE TITLE
useLocalStorageValue incorrect default value on SSR

### ISSUE THREAD

**Issue by nghiepit** [react-hookz/web#332]
### What is the current behavior?

What does `@react-hookz/web` do right now.
**9.0.0**

### Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/s/inspiring-gauss-x2l6x?file=/pages/index.js:40-60 or similar.

### What is the expected behavior?
Currently, defaultValue are different on client and SSR. On SSR defaultValue always is`undefined`

**Comment by xobotyi** [comment]
It is not a bug, default value is set when there is no entry, SSR is unable to check it, as there is no local storage, therefore it always returns `undefined`.
