### ISSUE TITLE
Create an example for `useCustomCompareEffect`

### ISSUE THREAD

**Issue by JoeDuncko** [react-hookz/web#352]
## What docs page needs to be fixed?

- **Section**:
- **Page**:

## What is the problem?

Currently `useCustomCompareEffect` does not have an example in the docs. 

## What should be changed to fix the problem?

We should make one.

**Comment by Rey-Wang** [comment]
@JoeDuncko one quick question, are we going to also include in `useDeepcompareEffect` or just keep `useCustomCompareEffect` is enough?

**Comment by JoeDuncko** [comment]
@xobotyi can probably answer that better than me @Rey-Wang

**Comment by xobotyi** [comment]
@Rey-Wang it is planned, as soon as I get well (currently in the bed with a cold)

**Comment by Rey-Wang** [comment]
@xobotyi hope you get better!!
