### ISSUE TITLE
`yarn check --verify-tree` failed because of wrong `@types/react` and `@types/react-dom` versions

### ISSUE THREAD

**Issue by Rey-Wang** [react-hookz/web#353]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.
No

### What is the current behavior?

What does `@react-hookz/web` do right now.
seems `@react-hookz/web` only support React 17+

### Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.

run `yarn check --verify-tree` in a React 16 project

### What is the expected behavior?

What should `@react-hookz/web` be doing?
it should also support React 16 +

### Environment Details

- _`@react-hookz/web` version:_ 11.1.1
- _`react` version:_  16.14.4
- _`react-dom` version:_ 16.9.11 
- _`typescript` version:_ 4.3.5

![image](https://user-images.githubusercontent.com/45580554/135228091-2aa8160b-e4d8-4c6a-a8d8-8849e1b4a55b.png)

**Comment by xobotyi** [comment]
Well it is better to exclude types then, besides recomendation to use it as dependencies.
