### ISSUE TITLE
`useMediaQuery` code example typo

### ISSUE THREAD

**Issue by malcodeman** [react-hookz/web#362]
## What docs page needs to be fixed?

- **Section**:
- **Page**: https://react-hookz.github.io/web/?path=/docs/sensor-usemediaquery--example

## What is the problem?

Typo `const isSmallDevise`

## What should be changed to fix the problem?

Should be `const isSmallDevice`

**Comment by Rey-Wang** [comment]
@xobotyi submit a simple fixes [PR](https://github.com/react-hookz/web/pull/383)
