### ISSUE TITLE
Wishlist of next functions to build/migrate from react-use

### ISSUE THREAD

**Issue by aifeipeng** [react-hookz/web#452]
## New Features
We have been using react-use, but now got into trouble with typescript. So we're looking into migrating to something else. So basically we are using these from react-use which has not yet been implemented in react-hookz. So this is basically a wishlist from our side 😸 
- `useInterval`
- `usePreviousDistinct`
- `useWindowSize`
- `useHover`
- `useCustomCompareEffect`
- `useCopyToClipboard`

**Comment by xobotyi** [comment]
`useCustomCompareEffect` already exists, btw - https://react-hookz.github.io/web/?path=/docs/lifecycle-usecustomcompareeffect--example

**Comment by aifeipeng** [comment]
We made custom hooks for the ones that did not exist. Thank you

**Comment by xobotyi** [comment]
@bboydflo added hook that can help with that [useIntervalEffect](https://react-hookz.github.io/web/?path=/docs/lifecycle-useintervaleffect--example)

**Comment by bboydflo** [comment]
> @bboydflo added hook that can help with that [useIntervalEffect](https://react-hookz.github.io/web/?path=/docs/lifecycle-useintervaleffect--example)

Thank you!
