### ISSUE TITLE
`useLocalStorageValue` crashes when used via a `data:` URL

### ISSUE THREAD

**Issue by JoeDuncko** [react-hookz/web#521]
### Prior Issues

Nope

### What is the current behavior?

When you load a page via a `data:` url that uses `useLocalStorageValue`, the hook crashes with the current error: 

`Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.` 

### Steps to Reproduce

I'm not sure of the best way to reproduce this. My team hits the bug when we accidentally hit our frontend via [Insomnia](https://insomnia.rest/).

### What is the expected behavior?

I really don't know. At least not crash, probably, but I don't know what results the hook should give, if any.

I'm mostly making this report in case anyone else hits this bug.

### Environment Details

- _`@react-hookz/web` version:_ 12.0.0
- _`react` version:_ 17.0.2
- _`react-dom` version:_ 17.0.2
- _`typescript` version:_ n/a
- _OS:_ macOS 12.0.1
- _Browser:_  Insomnia 2021.7.2 
- _Did this work in previous versions?_ Not sure

**Comment by xobotyi** [comment]
guesss we have to fallback to `undefined` in case of inaccessibility of storages
