### ISSUE TITLE
Rename source files to index.ts under each respective directory

### ISSUE THREAD

**Issue by zhoutwo** [react-hookz/web#538]
### What is the new or updated feature that you are suggesting?
For each source file, rename the file to index.ts. For example, change `src/useUpdateEffect/useUpdateEffect.ts` to `src/useUpdateEffect/index.ts` 

### Why should this feature be included?
This will make the import look more concise. Instead of `@react-hookz/web/esnext/useUpdateEffect/useUpdateEffect`, we can use `@react-hookz/web/esnext/useUpdateEffect` instead.

**Comment by zhoutwo** [comment]
As a migration path, create (not rename) index.ts and write something like `export { useUpdateEffect } from './useUpdateEffect';` while keeping the `useUpdateEffect.ts` file. This will make sure existing library users are not broken.

**Comment by xobotyi** [comment]
@JoeDuncko wdyt?

**Comment by zhoutwo** [comment]
Oh, maybe just `@react-hookz/web/esnext` works, but want to make sure if this also supports things like tree-shaking, as in, will `@react-hookz/web/esnext` automatically load all the files?

**Comment by xobotyi** [comment]
@zhoutwo this pacakge is treeshakable, so there should be no issues with importing from root index files.

**Comment by zhoutwo** [comment]
Got it. Let me experiment with it more, thank you for the clarification!
