### ISSUE TITLE
Create an example for `useDeepCompareEffect`

### ISSUE THREAD

**Issue by JoeDuncko** [react-hookz/web#582]
## What docs page needs to be fixed?

- **Section**:
- **Page**:

## What is the problem?

Currently `useDeepCompareEffect` does not have an example in the docs. 

## What should be changed to fix the problem?

We should make one.

**Comment by xobotyi** [comment]
Also, for `useCustomCompareEffect`

**Comment by kylemh** [comment]
For `useDeepCompareEffect`, how about [this](https://github.com/kentcdodds/use-deep-compare-effect)?

For `useCustomCompareEffects`, how about comparing 2 objects by hashing them and comparing their hashes rather than a deep compare?

**Comment by JoeDuncko** [comment]
> Also, for `useCustomCompareEffect`

That's a separate issue, https://github.com/react-hookz/web/issues/352

@kylemh I really like the hash comparison for `useCustomCompareEffect`.
