### ISSUE TITLE
Create new Hook, useRefGetter

### ISSUE THREAD

**Issue by ruggi99** [react-hookz/web#686]
### What is the new or updated feature that you are suggesting?
Hi all,
this is a great library.
I think it's missing a hook.
I'd like to have a hook that returns a costant function that returns a mutable value.
It's like having a syncedRef and returning a costant function that returns the current value of the ref

```javascript
function useRefGetter(value) {
  const myRef = useSyncedRef(value)
  return useCallback(() => myRef.current, [myRef])
}

function Component() {
  const valueGetter = useRefGetter(value);
  return <Component2 valueFn={valueGetter} />;
}

function Component2({valueFn}) {
  return <div>{valueFn()}</div>;
}
```

### Why should this feature be included?
I think it's a syntatic sugar instead of using refs (and .current property).

Thanks in advance

**Comment by ruggi99** [comment]
Is this the `useGetSet` from `react-use`?

**Comment by xobotyi** [comment]
`useGetSet` is from `useState` side.
I'll think about implementing that one when free time will occur =)

**Comment by xobotyi** [comment]
After a time - i dont think that we will implement it.
`useRef` along with `useSyncedRef` is more versatile approach and your proposal looks like a syncatic sugar, that would be rarely used, therefore i think it is better to leave this one be implement on need by developers.
