### ISSUE TITLE
useSet delete call causes react to rerender but shows stale UI

### ISSUE THREAD

**Issue by mario-jerkovic** [react-hookz/web#691]
### Prior Issues

I cannot see any releated issues.

### What is the current behavior?

When using `useSet` hook and calling delete method multiple times in sequence and leaving at least one item in set React component will re-render but UI will show stale values.

### Steps to Reproduce

You can find full reproduction on [codesanbox](https://codesandbox.io/s/react-hookz-set-bug-fniw4e?file=/src/App.tsx). 
I have one example which is using **@react-hookz** `useSet`  and one with copy/paste of the same `useSet` hook but the only change is in `useRerender` hook which is not switching boolean but increasing integer **which fixes this bug**.

### What is the expected behavior?

When calling delete on Set provided by the `useSet` hook UI should reflect the latest state

### Environment Details

- _`@react-hookz/web` version:_ 13.1.0
- _`react` version:_ 17.0.2
- _`react-dom` version:_ 17.0.2
- _`typescript` version:_ 4.4.2
- _OS:_ Mac OS 12.2.1
- _Browser:_ Chrome 99.0.4844.83
- _Did this work in previous versions?_ No

**Comment by xobotyi** [comment]
Welp, this one seems to be caused by batching.
I'll fix it sometime soon.
