### ISSUE TITLE
bug useNetworkState

### ISSUE THREAD

**Issue by Oxicode** [react-hookz/web#697]
### What is the current behavior?
`"type": "unknown"`

### Steps to Reproduce

Go to https://react-hookz.github.io/web/?path=/docs/navigator-usenetworkstate--example

### What is the expected behavior?

`"type": "Wifi"`
 
![image](https://user-images.githubusercontent.com/1320709/161188413-0fe27d8a-6878-42a7-95d7-759dfd149386.png)

**Comment by xobotyi** [comment]
The state is taken from browser API as-is, there is nothing we can do with it!

**Comment by xobotyi** [comment]
Besides from that, on my android phone everything works fine, and wifi is detected properly. ![Screenshot_20220401-072231.jpg](https://user-images.githubusercontent.com/6178739/161194597-bd874946-67ba-40ef-a9eb-7a4fcd965a17.jpg)
