### ISSUE TITLE
Eventually ignore React events in useToggle hook

### ISSUE THREAD

**Issue by ruggi99** [react-hookz/web#706]
Hi all,
I tried to use `useToggle` on a `<button>` to toggle a menu but it doesn't work because when used directly in a `<button>` the first argument is always the event fired.
```js
function MyComponent() {
  const [state, toggleState] = useToggle(false);
  return <button onClick={toggleState}>Toggle me!<button>
}
```

I'm wondering if we can ignore the first argument if it is an event (or a click event in this case).
The workaround for now is using `onClick={() => toggleState()}` but is not stable across renders.
Thanks

**Comment by xobotyi** [comment]
What do you mean by not stable? Changing from render to render? Then wrap handler witn `useCallback`.

`useToggle` is a `useState` wrapper with guard to be a boolean, and reverse in case state setter called w\o parameter. You not likely want to use it's setter as `onClick` handler.
