### ISSUE TITLE
useFirstMountState hook is broken

### ISSUE THREAD

**Issue by AuthorProxy** [react-hookz/web#734]
Added  `const isFirstMount = useRootSelector(useFirstMountState);` to the first line of component broke the whole app.

    "@react-hookz/web": "^12.0.0",

index.js:1 Warning: React has detected a change in the order of Hooks called by PlaylistAutocompleteRaw. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useReducer                 useReducer
3. useMemo                    useMemo
4. useRef                     useRef
5. useRef                     useRef
6. useRef                     useRef
7. useRef                     useRef
8. useRef                     useLayoutEffect

**Comment by xobotyi** [comment]
What is `useRootSelector`?
Never had an issue with `useFirstMountState`🤔
