### ISSUE TITLE
Feature request: Default exports in individual files

### ISSUE THREAD

**Issue by icopp** [react-hookz/web#882]
### What is the new or updated feature that you are suggesting?

It would be useful if hooks were provided as default exports when importing directly from a given file.

For example, currently to directly import `useUnmountEffect` I have to use a statement like:

```js
import { useUnmountEffect } from '@react-hookz/web/cjs/useUnmountEffect/useUnmountEffect';
```

It would help if I could also use an import like this:

```js
import useUnmountEffect from '@react-hookz/web/cjs/useUnmountEffect/useUnmountEffect';
```

### Why should this feature be included?

There's various build tooling, intended for cases like this library, Lodash, etc, that can rewrite imports like this...

```js
import {
  thingA,
  thingB,
  thingC
} from 'some-library'
```

to look like this at build time, using string matching.

```js
import thingA from 'some-library/thingA'
import thingB from 'some-library/thingB'
import thingC from 'some-library/thingA'
```

This tooling generally assumes that any individual exports will be the default export in the specific file, since that's the pattern followed by major libraries like Lodash. Having default exports would allow using that tooling.

**Comment by jpwallace22** [comment]
I would be able to set this up if the general consensus agrees with the feature. Not a lot of discussion on it, so not sure if there is a reason it hasn't been done yet.

**Comment by xobotyi** [comment]
aaabout this one. it is kinda janky theme to start, but here we are.
1) adding default export will increas overall package size for @react-hookz/web
2) the fact lodash uses it does not mean it is coreect and\or the proper way
3) i cant really see why
    ```ts
    import {  thingA,  thingB, thingC } from 'some-library';
    ```
    considered worse than
    ```ts
    import thingA from 'some-library/thingA';
    import thingB from 'some-library/thingB';
    import thingC from 'some-library/thingA';
    ```
    Second approach will lead to larger bundle than first one (even after munging)
