### ISSUE TITLE
`useMountEffect` can't return a clean-up function

### ISSUE THREAD

**Issue by nuanyang233** [react-hookz/web#90]
### What is the current behavior?

```
export function useMountEffect(effect: CallableFunction): void {
  useEffect(() => {
    effect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
}

```

### Steps to Reproduce

When the `effect` returns a clean-up function, the function can't be working.

### What is the expected behavior?

Sometimes, we hope to subscribe to something(like WebSocket?) when the component be mounted. And we must unsubscribe it when the component is unmounted. Currently useMountEffect does not support returning a clean-up function.

Perhaps it needs to be changed to

```
export function useMountEffect(effect: CallableFunction): void {
  useEffect(
    () => effect(),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );
}
```

**Comment by xobotyi** [comment]
This is not a bug and done intentionally.

In case you need a cleanup - simply use `useEffect` with empty dependencies list, there is no reason for `react-hookz` to rewrap default hook.

**Comment by nuanyang233** [comment]
ok, I get it. But I think many of you who are used to using react-use like I am will find this ambiguous.

**Comment by xobotyi** [comment]
No need to cloase as ill collect opinions.

As for me it is unabiguos since we're invoking the `mount effect`, as it said in the name, cleanup is about unmount stage.

**Comment by nuanyang233** [comment]
> No need to cloase as ill collect opinions.
> 
> As for me it is unabiguos since we're invoking the `mount effect`, as it said in the name, cleanup is about unmount stage.

But sometimes in the clean-up function, we need the closure to get something in the effector

4ex:

```
useEffect(() => {
    const id = subscribe(something)
    return () => {
        unsubscribe(id)
    }
},[])

```

If this scenario exists, we execute the effector in the `useMountEffect` as you said, and execute the Unsubscribe in the unmount hook, the `id` passing will become problematic

**Comment by xobotyi** [comment]
I'm talking that in case anyone need the cleanup - simply use `useEffect` with empty dependencies list.

The only con here is linter will freak about it.

**Comment by avxit** [comment]
> I'm talking that in case anyone need the cleanup - simply use `useEffect` with empty dependencies list.
> 
> The only con here is that linter will freak about it.

Same though, I think rewrap `useEffect` and disable linter doesn't make any sense. It's against design of `useEffect` hook. Just use `useEffect` and disable the linter yourself if needed so that you know "I'm doing this intentionally because ..." (but don't do that, if you want to optimize, do the way the document shows you [here](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects)).
