### ISSUE TITLE
not compatible when useEventListener(globalThis, ...)

### ISSUE THREAD

**Issue by Himself65** [react-hookz/web#961]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

### What is the current behavior?

```shell
TS2345: Argument of type 'typeof globalThis' is not assignable to parameter of type 'EventTarget | RefObject  | null'.
```

### Steps to Reproduce

```tsx
useEventListener(
    globalThis,
    'keydown',
    (event: KeyboardEvent) => {
       // ...
    }
)
```

### What is the expected behavior?

Don't throw error

### Environment Details

- _`@react-hookz/web` version:_ 16.0.0
- _`react` 18.2.0
- _`react-dom` 18.2.0
- _`typescript` 4.8.4
- _Did this work in previous versions?_

**Comment by xobotyi** [comment]
@ArttuOll could you please take care of this one?

**Comment by ArttuOll** [comment]
I'll take a look tomorrow/next week.

**Comment by ArttuOll** [comment]
> The reason I use globalThis instead of window or document is because next.js SSR step will throw error because they doesn't exist at the time

Hmm... So maybe the real problem is  #978?

**Comment by Himself65** [comment]
> > The reason I use globalThis instead of window or document is because next.js SSR step will throw error because they doesn't exist at the time
> 
> 
> 
> Hmm... So maybe the real problem is  #978?

I think so, but use globalThis is a workaround, only emit type error

**Comment by ArttuOll** [comment]
I think this should be closed in favor of #978 because that seems to be the root issue here.

**Comment by xobotyi** [comment]
@Himself65 what types do you use for `globalThis`? in typescript it defaults to any and therefore does not emit any error.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/6178739/204224323-6fc05707-cfbb-4223-b0ef-051a53ebde3a.png">

**Comment by ArttuOll** [comment]
I wonder if this changed with the latest version of TypeScript? Because I remember testing this and I saw an error.
