### ISSUE TITLE
Raise the cjs and esm target to es6

### ISSUE THREAD

**Issue by wesgro** [react-hookz/web#962]
## New Features

The ESM and CJS targets use es6 instead of es5

All evergreen browsers fully support the ES6 spec (Even Safari as of Safari 10)

Generating ES5 compliant code introduces unnecessary feature polyfills that can bloat bundles and possibly create warnings in rollup (no top level `this` for example).

### What is the new or updated feature that you are suggesting?

Change the `target` properties for the CJS and ESM builds to use es6 instead of es5

### Why should this feature be included?

Since this library supports React 18 and React 18 no longer supports IE 11 this seems like a good time to raise the floor of the non-ESNext generated code.

If users of this library need to support IE 11 still they can always include this library in their babel config to transpile it down to whatever ES version they need to support.

**Comment by xobotyi** [comment]
@wesgro in closest release CJS version will be returned🙃
